//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comercializacion.Client.UserService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserResponse", Namespace="http://schemas.datacontract.org/2004/07/UserManagement.Reponse")]
    [System.SerializableAttribute()]
    public partial class UserResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResetPasswordTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SessionTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SystemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comercializacion.Client.UserService.UserAdmin UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comercializacion.Client.UserService.UserSystemAdmin[] UserPermissionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comercializacion.Client.UserService.UserAdmin[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResetPasswordToken {
            get {
                return this.ResetPasswordTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ResetPasswordTokenField, value) != true)) {
                    this.ResetPasswordTokenField = value;
                    this.RaisePropertyChanged("ResetPasswordToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SessionToken {
            get {
                return this.SessionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionTokenField, value) != true)) {
                    this.SessionTokenField = value;
                    this.RaisePropertyChanged("SessionToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemId {
            get {
                return this.SystemIdField;
            }
            set {
                if ((this.SystemIdField.Equals(value) != true)) {
                    this.SystemIdField = value;
                    this.RaisePropertyChanged("SystemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comercializacion.Client.UserService.UserAdmin User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comercializacion.Client.UserService.UserSystemAdmin[] UserPermissions {
            get {
                return this.UserPermissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPermissionsField, value) != true)) {
                    this.UserPermissionsField = value;
                    this.RaisePropertyChanged("UserPermissions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comercializacion.Client.UserService.UserAdmin[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAdmin", Namespace="http://schemas.datacontract.org/2004/07/UserManagement.Usuario")]
    [System.SerializableAttribute()]
    public partial class UserAdmin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comercializacion.Client.UserService.UserRole[] User_RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime User_date_createdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_father_surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_given_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_mother_surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime User_password_date_changedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_password_hashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_password_iterationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_password_saltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Password {
            get {
                return this.User_PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.User_PasswordField, value) != true)) {
                    this.User_PasswordField = value;
                    this.RaisePropertyChanged("User_Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comercializacion.Client.UserService.UserRole[] User_Roles {
            get {
                return this.User_RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.User_RolesField, value) != true)) {
                    this.User_RolesField = value;
                    this.RaisePropertyChanged("User_Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime User_date_created {
            get {
                return this.User_date_createdField;
            }
            set {
                if ((this.User_date_createdField.Equals(value) != true)) {
                    this.User_date_createdField = value;
                    this.RaisePropertyChanged("User_date_created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_email {
            get {
                return this.User_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.User_emailField, value) != true)) {
                    this.User_emailField = value;
                    this.RaisePropertyChanged("User_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_father_surname {
            get {
                return this.User_father_surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_father_surnameField, value) != true)) {
                    this.User_father_surnameField = value;
                    this.RaisePropertyChanged("User_father_surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_given_name {
            get {
                return this.User_given_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_given_nameField, value) != true)) {
                    this.User_given_nameField = value;
                    this.RaisePropertyChanged("User_given_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_id {
            get {
                return this.User_idField;
            }
            set {
                if ((this.User_idField.Equals(value) != true)) {
                    this.User_idField = value;
                    this.RaisePropertyChanged("User_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_mother_surname {
            get {
                return this.User_mother_surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_mother_surnameField, value) != true)) {
                    this.User_mother_surnameField = value;
                    this.RaisePropertyChanged("User_mother_surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_name {
            get {
                return this.User_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_nameField, value) != true)) {
                    this.User_nameField = value;
                    this.RaisePropertyChanged("User_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime User_password_date_changed {
            get {
                return this.User_password_date_changedField;
            }
            set {
                if ((this.User_password_date_changedField.Equals(value) != true)) {
                    this.User_password_date_changedField = value;
                    this.RaisePropertyChanged("User_password_date_changed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_password_hash {
            get {
                return this.User_password_hashField;
            }
            set {
                if ((object.ReferenceEquals(this.User_password_hashField, value) != true)) {
                    this.User_password_hashField = value;
                    this.RaisePropertyChanged("User_password_hash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_password_iteration {
            get {
                return this.User_password_iterationField;
            }
            set {
                if ((this.User_password_iterationField.Equals(value) != true)) {
                    this.User_password_iterationField = value;
                    this.RaisePropertyChanged("User_password_iteration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_password_salt {
            get {
                return this.User_password_saltField;
            }
            set {
                if ((object.ReferenceEquals(this.User_password_saltField, value) != true)) {
                    this.User_password_saltField = value;
                    this.RaisePropertyChanged("User_password_salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_status {
            get {
                return this.User_statusField;
            }
            set {
                if ((this.User_statusField.Equals(value) != true)) {
                    this.User_statusField = value;
                    this.RaisePropertyChanged("User_status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSystemAdmin", Namespace="http://schemas.datacontract.org/2004/07/UserManagement.Usuario")]
    [System.SerializableAttribute()]
    public partial class UserSystemAdmin : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Allows_multiple_sessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Evento_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int System_admin_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_role_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool User_system_adminField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Allows_multiple_sessions {
            get {
                return this.Allows_multiple_sessionsField;
            }
            set {
                if ((this.Allows_multiple_sessionsField.Equals(value) != true)) {
                    this.Allows_multiple_sessionsField = value;
                    this.RaisePropertyChanged("Allows_multiple_sessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Evento_id {
            get {
                return this.Evento_idField;
            }
            set {
                if ((this.Evento_idField.Equals(value) != true)) {
                    this.Evento_idField = value;
                    this.RaisePropertyChanged("Evento_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int System_admin_id {
            get {
                return this.System_admin_idField;
            }
            set {
                if ((this.System_admin_idField.Equals(value) != true)) {
                    this.System_admin_idField = value;
                    this.RaisePropertyChanged("System_admin_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_id {
            get {
                return this.User_idField;
            }
            set {
                if ((this.User_idField.Equals(value) != true)) {
                    this.User_idField = value;
                    this.RaisePropertyChanged("User_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_role_id {
            get {
                return this.User_role_idField;
            }
            set {
                if ((this.User_role_idField.Equals(value) != true)) {
                    this.User_role_idField = value;
                    this.RaisePropertyChanged("User_role_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool User_system_admin {
            get {
                return this.User_system_adminField;
            }
            set {
                if ((this.User_system_adminField.Equals(value) != true)) {
                    this.User_system_adminField = value;
                    this.RaisePropertyChanged("User_system_admin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://schemas.datacontract.org/2004/07/UserManagement.Usuario")]
    [System.SerializableAttribute()]
    public partial class UserRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int System_admin_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool User_is_system_adminField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_role_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_role_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_role_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Comercializacion.Client.UserService.RolePermission[] User_role_permissionsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int System_admin_id {
            get {
                return this.System_admin_idField;
            }
            set {
                if ((this.System_admin_idField.Equals(value) != true)) {
                    this.System_admin_idField = value;
                    this.RaisePropertyChanged("System_admin_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool User_is_system_admin {
            get {
                return this.User_is_system_adminField;
            }
            set {
                if ((this.User_is_system_adminField.Equals(value) != true)) {
                    this.User_is_system_adminField = value;
                    this.RaisePropertyChanged("User_is_system_admin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_role_description {
            get {
                return this.User_role_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.User_role_descriptionField, value) != true)) {
                    this.User_role_descriptionField = value;
                    this.RaisePropertyChanged("User_role_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_role_id {
            get {
                return this.User_role_idField;
            }
            set {
                if ((this.User_role_idField.Equals(value) != true)) {
                    this.User_role_idField = value;
                    this.RaisePropertyChanged("User_role_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_role_name {
            get {
                return this.User_role_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_role_nameField, value) != true)) {
                    this.User_role_nameField = value;
                    this.RaisePropertyChanged("User_role_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Comercializacion.Client.UserService.RolePermission[] User_role_permissions {
            get {
                return this.User_role_permissionsField;
            }
            set {
                if ((object.ReferenceEquals(this.User_role_permissionsField, value) != true)) {
                    this.User_role_permissionsField = value;
                    this.RaisePropertyChanged("User_role_permissions");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolePermission", Namespace="http://schemas.datacontract.org/2004/07/UserManagement.Usuario")]
    [System.SerializableAttribute()]
    public partial class RolePermission : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_permission_descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Role_permission_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Role_permission_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int System_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role_permission_description {
            get {
                return this.Role_permission_descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_permission_descriptionField, value) != true)) {
                    this.Role_permission_descriptionField = value;
                    this.RaisePropertyChanged("Role_permission_description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Role_permission_id {
            get {
                return this.Role_permission_idField;
            }
            set {
                if ((this.Role_permission_idField.Equals(value) != true)) {
                    this.Role_permission_idField = value;
                    this.RaisePropertyChanged("Role_permission_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role_permission_name {
            get {
                return this.Role_permission_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Role_permission_nameField, value) != true)) {
                    this.Role_permission_nameField = value;
                    this.RaisePropertyChanged("Role_permission_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int System_id {
            get {
                return this.System_idField;
            }
            set {
                if ((this.System_idField.Equals(value) != true)) {
                    this.System_idField = value;
                    this.RaisePropertyChanged("System_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSessionToken", Namespace="http://schemas.datacontract.org/2004/07/UserManagement.Usuario")]
    [System.SerializableAttribute()]
    public partial class UserSessionToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Evento_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int System_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Token_created_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Token_expire_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Token_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Token_statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_Id_ExternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_agentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_browser_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_host_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int User_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_raw_urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Evento_id {
            get {
                return this.Evento_idField;
            }
            set {
                if ((this.Evento_idField.Equals(value) != true)) {
                    this.Evento_idField = value;
                    this.RaisePropertyChanged("Evento_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int System_id {
            get {
                return this.System_idField;
            }
            set {
                if ((this.System_idField.Equals(value) != true)) {
                    this.System_idField = value;
                    this.RaisePropertyChanged("System_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Token_created_date {
            get {
                return this.Token_created_dateField;
            }
            set {
                if ((this.Token_created_dateField.Equals(value) != true)) {
                    this.Token_created_dateField = value;
                    this.RaisePropertyChanged("Token_created_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Token_expire_date {
            get {
                return this.Token_expire_dateField;
            }
            set {
                if ((this.Token_expire_dateField.Equals(value) != true)) {
                    this.Token_expire_dateField = value;
                    this.RaisePropertyChanged("Token_expire_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token_id {
            get {
                return this.Token_idField;
            }
            set {
                if ((object.ReferenceEquals(this.Token_idField, value) != true)) {
                    this.Token_idField = value;
                    this.RaisePropertyChanged("Token_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Token_status {
            get {
                return this.Token_statusField;
            }
            set {
                if ((this.Token_statusField.Equals(value) != true)) {
                    this.Token_statusField = value;
                    this.RaisePropertyChanged("Token_status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_Id_Externo {
            get {
                return this.User_Id_ExternoField;
            }
            set {
                if ((this.User_Id_ExternoField.Equals(value) != true)) {
                    this.User_Id_ExternoField = value;
                    this.RaisePropertyChanged("User_Id_Externo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_agent {
            get {
                return this.User_agentField;
            }
            set {
                if ((object.ReferenceEquals(this.User_agentField, value) != true)) {
                    this.User_agentField = value;
                    this.RaisePropertyChanged("User_agent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_browser_name {
            get {
                return this.User_browser_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_browser_nameField, value) != true)) {
                    this.User_browser_nameField = value;
                    this.RaisePropertyChanged("User_browser_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_host_address {
            get {
                return this.User_host_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.User_host_addressField, value) != true)) {
                    this.User_host_addressField = value;
                    this.RaisePropertyChanged("User_host_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int User_id {
            get {
                return this.User_idField;
            }
            set {
                if ((this.User_idField.Equals(value) != true)) {
                    this.User_idField = value;
                    this.RaisePropertyChanged("User_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_raw_url {
            get {
                return this.User_raw_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.User_raw_urlField, value) != true)) {
                    this.User_raw_urlField = value;
                    this.RaisePropertyChanged("User_raw_url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUsers", ReplyAction="http://tempuri.org/IUser/GetUsersResponse")]
        Comercializacion.Client.UserService.UserResponse GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUsers", ReplyAction="http://tempuri.org/IUser/GetUsersResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CreateUser", ReplyAction="http://tempuri.org/IUser/CreateUserResponse")]
        Comercializacion.Client.UserService.UserResponse CreateUser(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSystemAdmin[] systemPermissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CreateUser", ReplyAction="http://tempuri.org/IUser/CreateUserResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> CreateUserAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSystemAdmin[] systemPermissions);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUser", ReplyAction="http://tempuri.org/IUser/UpdateUserResponse")]
        Comercializacion.Client.UserService.UserResponse UpdateUser(Comercializacion.Client.UserService.UserAdmin newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUser", ReplyAction="http://tempuri.org/IUser/UpdateUserResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> UpdateUserAsync(Comercializacion.Client.UserService.UserAdmin newUser);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LoginUsingSystemId", ReplyAction="http://tempuri.org/IUser/LoginUsingSystemIdResponse")]
        Comercializacion.Client.UserService.UserResponse LoginUsingSystemId(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, int systemId, System.DateTime expireDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LoginUsingSystemId", ReplyAction="http://tempuri.org/IUser/LoginUsingSystemIdResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LoginUsingSystemIdAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, int systemId, System.DateTime expireDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ValidateUser", ReplyAction="http://tempuri.org/IUser/ValidateUserResponse")]
        Comercializacion.Client.UserService.UserResponse ValidateUser(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ValidateUser", ReplyAction="http://tempuri.org/IUser/ValidateUserResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ValidateUserAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ExistUser", ReplyAction="http://tempuri.org/IUser/ExistUserResponse")]
        Comercializacion.Client.UserService.UserResponse ExistUser(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userRequest, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ExistUser", ReplyAction="http://tempuri.org/IUser/ExistUserResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ExistUserAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userRequest, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LoginUsingSystemName", ReplyAction="http://tempuri.org/IUser/LoginUsingSystemNameResponse")]
        Comercializacion.Client.UserService.UserResponse LoginUsingSystemName(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName, System.DateTime expireDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LoginUsingSystemName", ReplyAction="http://tempuri.org/IUser/LoginUsingSystemNameResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LoginUsingSystemNameAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName, System.DateTime expireDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LogInByCookieUsingSystemId", ReplyAction="http://tempuri.org/IUser/LogInByCookieUsingSystemIdResponse")]
        Comercializacion.Client.UserService.UserResponse LogInByCookieUsingSystemId(string userToken, int systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LogInByCookieUsingSystemId", ReplyAction="http://tempuri.org/IUser/LogInByCookieUsingSystemIdResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LogInByCookieUsingSystemIdAsync(string userToken, int systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LogInByCookieUsingSystemName", ReplyAction="http://tempuri.org/IUser/LogInByCookieUsingSystemNameResponse")]
        Comercializacion.Client.UserService.UserResponse LogInByCookieUsingSystemName(string userToken, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LogInByCookieUsingSystemName", ReplyAction="http://tempuri.org/IUser/LogInByCookieUsingSystemNameResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LogInByCookieUsingSystemNameAsync(string userToken, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LogOff", ReplyAction="http://tempuri.org/IUser/LogOffResponse")]
        Comercializacion.Client.UserService.UserResponse LogOff(string userToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/LogOff", ReplyAction="http://tempuri.org/IUser/LogOffResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LogOffAsync(string userToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GenerateResetPasswordToken", ReplyAction="http://tempuri.org/IUser/GenerateResetPasswordTokenResponse")]
        Comercializacion.Client.UserService.UserResponse GenerateResetPasswordToken(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GenerateResetPasswordToken", ReplyAction="http://tempuri.org/IUser/GenerateResetPasswordTokenResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> GenerateResetPasswordTokenAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ValidateResetToken", ReplyAction="http://tempuri.org/IUser/ValidateResetTokenResponse")]
        Comercializacion.Client.UserService.UserResponse ValidateResetToken(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ValidateResetToken", ReplyAction="http://tempuri.org/IUser/ValidateResetTokenResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ValidateResetTokenAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ChangePasswordByToken", ReplyAction="http://tempuri.org/IUser/ChangePasswordByTokenResponse")]
        Comercializacion.Client.UserService.UserResponse ChangePasswordByToken(string token, string userEmail, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ChangePasswordByToken", ReplyAction="http://tempuri.org/IUser/ChangePasswordByTokenResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ChangePasswordByTokenAsync(string token, string userEmail, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ChangeUserPassword", ReplyAction="http://tempuri.org/IUser/ChangeUserPasswordResponse")]
        Comercializacion.Client.UserService.UserResponse ChangeUserPassword(int userId, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ChangeUserPassword", ReplyAction="http://tempuri.org/IUser/ChangeUserPasswordResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ChangeUserPasswordAsync(int userId, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/IsValidUserTokenUsingSystemName", ReplyAction="http://tempuri.org/IUser/IsValidUserTokenUsingSystemNameResponse")]
        Comercializacion.Client.UserService.UserResponse IsValidUserTokenUsingSystemName(string userToken, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/IsValidUserTokenUsingSystemName", ReplyAction="http://tempuri.org/IUser/IsValidUserTokenUsingSystemNameResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> IsValidUserTokenUsingSystemNameAsync(string userToken, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/IsValidUserTokenUsingSystemId", ReplyAction="http://tempuri.org/IUser/IsValidUserTokenUsingSystemIdResponse")]
        Comercializacion.Client.UserService.UserResponse IsValidUserTokenUsingSystemId(string userToken, int systemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/IsValidUserTokenUsingSystemId", ReplyAction="http://tempuri.org/IUser/IsValidUserTokenUsingSystemIdResponse")]
        System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> IsValidUserTokenUsingSystemIdAsync(string userToken, int systemId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : Comercializacion.Client.UserService.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<Comercializacion.Client.UserService.IUser>, Comercializacion.Client.UserService.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Comercializacion.Client.UserService.UserResponse GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public Comercializacion.Client.UserService.UserResponse CreateUser(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSystemAdmin[] systemPermissions) {
            return base.Channel.CreateUser(user, systemPermissions);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> CreateUserAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSystemAdmin[] systemPermissions) {
            return base.Channel.CreateUserAsync(user, systemPermissions);
        }
        
        public Comercializacion.Client.UserService.UserResponse UpdateUser(Comercializacion.Client.UserService.UserAdmin newUser) {
            return base.Channel.UpdateUser(newUser);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> UpdateUserAsync(Comercializacion.Client.UserService.UserAdmin newUser) {
            return base.Channel.UpdateUserAsync(newUser);
        }
        
        public Comercializacion.Client.UserService.UserResponse LoginUsingSystemId(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, int systemId, System.DateTime expireDate) {
            return base.Channel.LoginUsingSystemId(user, userToken, systemId, expireDate);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LoginUsingSystemIdAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, int systemId, System.DateTime expireDate) {
            return base.Channel.LoginUsingSystemIdAsync(user, userToken, systemId, expireDate);
        }
        
        public Comercializacion.Client.UserService.UserResponse ValidateUser(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName) {
            return base.Channel.ValidateUser(user, userToken, systemName);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ValidateUserAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName) {
            return base.Channel.ValidateUserAsync(user, userToken, systemName);
        }
        
        public Comercializacion.Client.UserService.UserResponse ExistUser(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userRequest, string systemName) {
            return base.Channel.ExistUser(user, userRequest, systemName);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ExistUserAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userRequest, string systemName) {
            return base.Channel.ExistUserAsync(user, userRequest, systemName);
        }
        
        public Comercializacion.Client.UserService.UserResponse LoginUsingSystemName(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName, System.DateTime expireDate) {
            return base.Channel.LoginUsingSystemName(user, userToken, systemName, expireDate);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LoginUsingSystemNameAsync(Comercializacion.Client.UserService.UserAdmin user, Comercializacion.Client.UserService.UserSessionToken userToken, string systemName, System.DateTime expireDate) {
            return base.Channel.LoginUsingSystemNameAsync(user, userToken, systemName, expireDate);
        }
        
        public Comercializacion.Client.UserService.UserResponse LogInByCookieUsingSystemId(string userToken, int systemId) {
            return base.Channel.LogInByCookieUsingSystemId(userToken, systemId);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LogInByCookieUsingSystemIdAsync(string userToken, int systemId) {
            return base.Channel.LogInByCookieUsingSystemIdAsync(userToken, systemId);
        }
        
        public Comercializacion.Client.UserService.UserResponse LogInByCookieUsingSystemName(string userToken, string systemName) {
            return base.Channel.LogInByCookieUsingSystemName(userToken, systemName);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LogInByCookieUsingSystemNameAsync(string userToken, string systemName) {
            return base.Channel.LogInByCookieUsingSystemNameAsync(userToken, systemName);
        }
        
        public Comercializacion.Client.UserService.UserResponse LogOff(string userToken) {
            return base.Channel.LogOff(userToken);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> LogOffAsync(string userToken) {
            return base.Channel.LogOffAsync(userToken);
        }
        
        public Comercializacion.Client.UserService.UserResponse GenerateResetPasswordToken(string email) {
            return base.Channel.GenerateResetPasswordToken(email);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> GenerateResetPasswordTokenAsync(string email) {
            return base.Channel.GenerateResetPasswordTokenAsync(email);
        }
        
        public Comercializacion.Client.UserService.UserResponse ValidateResetToken(string token) {
            return base.Channel.ValidateResetToken(token);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ValidateResetTokenAsync(string token) {
            return base.Channel.ValidateResetTokenAsync(token);
        }
        
        public Comercializacion.Client.UserService.UserResponse ChangePasswordByToken(string token, string userEmail, string newPassword) {
            return base.Channel.ChangePasswordByToken(token, userEmail, newPassword);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ChangePasswordByTokenAsync(string token, string userEmail, string newPassword) {
            return base.Channel.ChangePasswordByTokenAsync(token, userEmail, newPassword);
        }
        
        public Comercializacion.Client.UserService.UserResponse ChangeUserPassword(int userId, string oldPassword, string newPassword) {
            return base.Channel.ChangeUserPassword(userId, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> ChangeUserPasswordAsync(int userId, string oldPassword, string newPassword) {
            return base.Channel.ChangeUserPasswordAsync(userId, oldPassword, newPassword);
        }
        
        public Comercializacion.Client.UserService.UserResponse IsValidUserTokenUsingSystemName(string userToken, string systemName) {
            return base.Channel.IsValidUserTokenUsingSystemName(userToken, systemName);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> IsValidUserTokenUsingSystemNameAsync(string userToken, string systemName) {
            return base.Channel.IsValidUserTokenUsingSystemNameAsync(userToken, systemName);
        }
        
        public Comercializacion.Client.UserService.UserResponse IsValidUserTokenUsingSystemId(string userToken, int systemId) {
            return base.Channel.IsValidUserTokenUsingSystemId(userToken, systemId);
        }
        
        public System.Threading.Tasks.Task<Comercializacion.Client.UserService.UserResponse> IsValidUserTokenUsingSystemIdAsync(string userToken, int systemId) {
            return base.Channel.IsValidUserTokenUsingSystemIdAsync(userToken, systemId);
        }
    }
}
